apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: notification
  namespace: accesslog-demo
spec:
  hosts:
    - notification-service
  http:
    - fault:
        delay:
          fixedDelay: 5s
          percentage:
            value: 100
      timeout: 1s
      route:
        - destination:
            host: notification-service
