# Reference solution for ats-016-lab-050-01.
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: access-logs
  namespace: accesslog-demo
spec:
  accessLogging:
    - providers:
        - name: envoy
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: notification
  namespace: accesslog-demo
spec:
  hosts:
    - notification-service
  http:
    - fault:
        delay:
          fixedDelay: 5s
          percentage:
            value: 100
      timeout: 2s
      route:
        - destination:
            host: notification-service
